language: python
python:
  - "2.7"
  - "3.6"
sudo: false
before_install:
  - sudo apt-get install -y netCDF4
install:
  - source activate test-environment
  - "python setup.py install"
script:
  - "nosetests -vs --with-coverage --cover-package=solar_index"
