language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
sudo: false
dist: xenial

before_install:
  - pip install netCDF4
  - pip install coveralls
install:
  - source activate test-environment
  - "python setup.py install"
script:
  - "nosetests -vs --with-coverage --cover-package=solar_index"
after_success: coveralls
