language: python
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

addons:
  apt:
    packages:
    - gfortran

before_install:
  - pip install matplotlib
  - pip install netCDF4
  - pip install coveralls
  - pip install pytest-cov
    # Prepare modified pysat install
  - pip install numpy
  - cd ..
  - echo 'cloning pysat'
  - git clone https://github.com/pysat/pysat.git >/dev/null
  - echo 'installing pysat'
  - cd ./pysat
  - git checkout no_sgp4
  # set up data directory
  - mkdir /home/travis/build/jklenzing/pysatData
  # install pysat
  - cd /home/travis/build/jklenzing/pysat
  - python setup.py install >/dev/null
  - cd /home/travis/build/jklenzing/solar_index

install:
  - source activate test-environment
  - python setup.py install
script:
  - pytest --cov=solar_index
after_success:
  - coveralls
